apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  annotations:
    kapp.k14s.io/change-group: "crossplane/aws-provider"
    kapp.k14s.io/change-rule: "upsert after upserting crossplane/config"
spec:
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.37.0
