apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: crossplane-aws-provider-config
  annotations:
    kapp.k14s.io/change-group: "crossplane/aws-provider-config"
    kapp.k14s.io/change-rule: "upsert after upserting crossplane/aws-provider"
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/jeffellin/tmc-experiments
      ref: main
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - gitops/crossplane-provider-config
  deploy:
  - kapp: {}
