---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: input-resource-reader
  namespace: continuousdelivery-resources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: input-resource-reader
  namespace: continuousdelivery-resources
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: input-resource-reader
  namespace: continuousdelivery-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: input-resource-reader
subjects:
- kind: ServiceAccount
  name: input-resource-reader

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: cluster-name-secret
  namespace: continuousdelivery-resources
spec:
  serviceAccountName: input-resource-reader # used to fetch input resources
  inputResources:
  - name: config
    ref:
      apiVersion: v1
      kind: ConfigMap
      name: stack-config
  template:
    type: generic
    stringData:
      values.yaml: |-
        cluster_name: $(.config.data.cluster_name)
        job: "foo"
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cluster-name-secret
  namespace: continuousdelivery-resources
spec:
  toNamespace: '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: cluster-name-secret
  namespace: ellin-system
spec:
  fromNamespace: continuousdelivery-resources
