#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def config():
#@ server = data.values.cluster_name
#@   if hasattr(data.values,server) and hasattr(data.values[server],"roles"):
#@     selected=server
#@   else:
#@    selected="default"
#@  end
#@    return data.values[selected]
#@ end      

#@ for val in config().roles:
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "tanzu-gitops-" + val.name
  namespace: continuousdelivery-resources
stringData:
#@ if hasattr(val,"options"):  
  values.yaml: #@ yaml.encode(val.options)
 
#@ end
#@ end      
