#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def config():
#@ server = data.values.cluster_name
#@   if hasattr(data.values,server) and hasattr(data.values[server],"roles"):
#@     selected=server
#@   else:
#@    selected="default"
#@  end
#@  if hasattr(data.values[selected],"options"):
#@    return data.values[selected].options
#@  else: 
#@    return selected
#@  end
#@ end      
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-gitops
  namespace: ellin-system
stringData:
  values.yaml: #@ yaml.encode(config())