#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ server = data.values.cluster_name
#@ def some_data():
#@   if hasattr(data.values,server) and hasattr(and data.values[server].profiles)):
#@     return data.values[server].profiles
#@   else:
#@    return data.values["default"].profiles
#@   end
#@ end
#@ for val in some_data():
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ "tmc-gitops-"+val
  labels:
     clusterName: #@ server
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/jeffellin/tmc-experiments
      ref: main
  template:
  - sops: 
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - #@ "gitops/" + val
      valuesFrom:
      - secretRef:
          name: cluster-name-secret
      - path: gitops/base/values.yaml
  deploy:
  - kapp: {}
 #@ end
