#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ server = data.values.cluster_name
#@   if hasattr(data.values,server) and hasattr(data.values[server],"roles"):
#@     selected=server
#@   else:
#@    selected="default"
#@  end
#@ def some_data():
#@     return data.values[selected].roles
#@ end
#@ for val in some_data():
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ "tmc-gitops-"+val.name
  labels:
     clusterName: #@ server
     configuration:  #@ selected
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/jeffellin/tmc-experiments
      ref: main
  template:
  - sops: 
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - #@ "gitops/" + val.name
      valuesFrom:
      - secretRef:
          name: cluster-name-secret
      - path: gitops/base/values/values.yaml
  deploy:
  - kapp: {}
 #@ end
