apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      version: 12.6.12
      sourceRef:
        kind: HelmRepository
        namespace: tanzu-helm-resources
        name: bitnami
      interval: 1m
  values:
    persistence:
      storageClass: nfs-client
      size: 500Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: minio.lab.ellin.net
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-contour-cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls: true
