#@ load("@ytt:data", "data")
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 5m0s
  provider: generic
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      version: 12.6.12
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      storageClass: nfs-client
      size: 500Gi
    ingress:
      enabled: true
      hosts:
       - #@ data.values.domain
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-contour-cluster-issuer
    tls:
      enabled: true