apiVersion: v1
kind: Secret
metadata:
    name: tap-remote-view-secrets
    namespace: tanzu-sync
type: Opaque
stringData:
    content.yaml: |-
        tap_install:
          values:
            tap_gui:
              app_config:
                  kubernetes:
                      serviceLocatorMethods:
                          type: 'multiTenant'
                      clusterLocatorMethods:
                          - type: 'config'
                            clusters:
                            - url: https://192.168.4.16:6443
                              name: tap-build
                              authProvider: serviceAccount
                              serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6InYxRGlaMnRqMDg4UWhfRHdGZHV0WmJOZU5xNThPekZWS0h0UExfWUU2Tk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDI3Nzg2YjUtNTdjMi00NzM0LTljNGItOTk3NjM5MzlkZmNjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.U-0R2kZp8fOvnkJn3zSMQB8253RcDPrvbAOUHMkgKjCBNJNac6Mc0TtJ8rnHSYyGA5kzKqwNCwjoRZcbqrwjscng4Bd-qiTRHS5P4gxIHUo3rEoXZy0Qd6Lm8xYpf5XkTKImGfu6O_P1f3Dbv8oG5v2AW81EdoLfyxPvkvp1SKq_6bJxJfcwBFXNJhGLpkqtVPFHo-qJ6fqwlEQ7ln6s87OoZ-xYSh16yGAmzcfrKdvtfILJT0SSLXJKzFsECdPqIst4Gv5UvLlrmzhmizIZ-WxRdz8wBv2VyublZgRyqeNHt5POgXDJ9yicdbd3DUddwISud2lbsdd_QQG98G7pVw
                              skipTLSVerify: true
                              skipMetricsLookup: true
                            - url: https://192.168.4.18:6443
                              name: tap-run
                              authProvider: serviceAccount
                              serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6InRKRlBrVE9sMW5iX0VWMy0zWnpXdnlaV2p5WmRQOVV2OTd2V1d5dTNycG8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNjJiODY0NWUtMjNhYS00NjI3LWFjNjQtNTg5YzJjNmU3MmVmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.BcIsWxQoDUBYMotn4rmwqGdsGW_LVGcM6iDlkH5j4ydVpZVINv3o3YON_7Ba1ERnQOzscdFJL2Q880y178KHMRKURRDARpcQxCTpbaaip78wVEouY8fv_OO_EbN0ArqKim9jisQJdP98gDQQzVVd68gr_qKyPhBrCMLveltJQlo2GAhFBjwZVEZ8AJmuyc9vhizK8JOM6iTYQnH8-VIL2TrM6nLq7vBnkgF_05wVLN4vjqLjSb5uRfy7VvZCS87J8lN_xj44KoB8cgd_wyAd1fxqPDYsfCWbw25FhmiWOaWWXBmJ0Bay_DNsse8ppPhV-xRAov7GiE_JtODbizzkBQ
                              skipTLSVerify: true
                              skipMetricsLookup: true
                            - url: https://192.168.4.17:6443
                              name: tap-iterate
                              authProvider: serviceAccount
                              serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IlRFZGVJRHpNb04tU3hMU2xCQVdSRkF0cDBXUDY1UGxvM0lPdmFKeWZTZUEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNGZlNzk3YTEtMGVmYi00OTdlLWFmNzYtMTAwMzc0MzMyMGM4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.0dfk2ahPDtM-mUMlxJWeTw37eBbKCzYDhRRdRkdIDQxnPttaitkHUvrAOIMo-aj8CAKwv2270vmmYM4dniZNdzMdRTSp6kf4iJtOkBk1Pgn7LiTweE2xYyn5sAC3VV1Qp7VcodaRlGYboNjBFinBFwbJQZb9000Vopk6KIDmGCQV4IrR6bP3eSzizTQf-llxWg2AVAC5DDrXg1fXXurCTWEeZj9uDso47Z1y5OwPOCbCw3nzoGZIvW0prwCeng19s91xvgvllRsCQteCG1clRqBdpuov1TCyWoTZTKR7-l8eG8320ypkG3oBV3TGEa3lyliJFxN_ix9vXKY30MP3Ug
                              skipTLSVerify: true
                              skipMetricsLookup: true
                  auth:
                      allowGuestAccess: true
