apiVersion: v1
kind: Secret
metadata:
    name: tap-remote-view-secrets
    namespace: tanzu-sync
type: Opaque
stringData:
    content.yaml: |
      tap_install:
        values:
          tap_gui:
            app_config:
                kubernetes:
                    serviceLocatorMethods:
                        type: 'multiTenant'
                    clusterLocatorMethods:
                        - type: 'config'
                          clusters:
                          - url: https://192.168.1.101:6443
                            name: tap-run
                            authProvider: serviceAccount
                            serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhJeXVWWVlzeVJ1OE03Z0thdmhxenl3YmxfQ1MwSDhxRVVyX3A3M01LWjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYWRkNDU5ZDUtMjdlZC00NTBiLThjMjItN2I0YWNiNjY4ZTJkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.XMQDmGyi00fNeoswyxrRV2k8jcjKhanyWedg6hPaHWcRoJkH0-U6MEVAwPe1x1F0FrY_7SuonYLMEk73NVKysvJ-39lX6svj-oBGe52_6EppIh4q08Ee6ZiEIRHCjVciBs9A52GHcspeHKa6su_riBTxZ-ZY19FhqIl3lgShPq121ID-BkRU08hdlVpKsgy3hLj51HsP4L9L3qLuAxbDVE9RmQedWs8VAsod9FLZDv_STXPreOoj3s_5SJlP0qAMOqV9OQIPBzVWR96aL6Gl7Sa4kATr92TzxjpMmNqoxZo7LUGrZU40OK0a0KtMlL5xSxg0H3FZYRnHXM2dqNSxZA
                            skipTLSVerify: true
                            skipMetricsLookup: true
                          - url: https://192.168.1.22:6443
                            name: tap-build
                            authProvider: serviceAccount
                            serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Im4xTnZoQVB3SkwxamoyZjVyUGNZOUhVSnprQzk3bmUyWi0tSVItM1JKN00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDZjYzY1YmQtZDU4YS00OGQ3LTgwMzQtM2MxNjI4OWEyNzQ3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.Hf4BT9q8spXpTM1wpfRIiNFmDkZOXxV_XkpLEh8OgwQ_VhKoqXNuTsUjomWMYKgyMZitArzRkDbwQ1Xs9Rs15PteEzdpQ2fXm4aH3biJsFo5AY9Zj5K395VfG80DtJui2xi7JNwlgfpD26xHezYI417B9Ew88E08iMJ_3Yj_swLrwIddeLoKfNCzH-wMv7OiTjVyf3Bw2aIFB4kWLM_Rdek8zVYw96IGgHBuwJueMb6XJekNQjInpjjZP1tQGBmkycrlmRzy32iZgqmxEgVu4KjJrXcL-YfYlP7nDQhpn9zH6QvY73ayBLGpi-1f3bQHPyuSjx0F0fnOaV0HmAqMHA
                            skipTLSVerify: true
                            skipMetricsLookup: true
                auth:
                    allowGuestAccess: true
