apiVersion: v1
kind: Secret
metadata:
    name: tap-remote-view-secrets
    namespace: tanzu-sync
type: Opaque
stringData:
    content.yaml: |-
        tap_install:
          values:
            tap_gui:
              app_config:
                  kubernetes:
                      serviceLocatorMethods:
                          type: 'multiTenant'
                      clusterLocatorMethods:
                          - type: 'config'
                            clusters:
                            - url: https://192.168.4.16:6443
                              name: tap-iterate
                              authProvider: serviceAccount
                              serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6InYxRGlaMnRqMDg4UWhfRHdGZHV0WmJOZU5xNThPekZWS0h0UExfWUU2Tk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDI3Nzg2YjUtNTdjMi00NzM0LTljNGItOTk3NjM5MzlkZmNjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.U-0R2kZp8fOvnkJn3zSMQB8253RcDPrvbAOUHMkgKjCBNJNac6Mc0TtJ8rnHSYyGA5kzKqwNCwjoRZcbqrwjscng4Bd-qiTRHS5P4gxIHUo3rEoXZy0Qd6Lm8xYpf5XkTKImGfu6O_P1f3Dbv8oG5v2AW81EdoLfyxPvkvp1SKq_6bJxJfcwBFXNJhGLpkqtVPFHo-qJ6fqwlEQ7ln6s87OoZ-xYSh16yGAmzcfrKdvtfILJT0SSLXJKzFsECdPqIst4Gv5UvLlrmzhmizIZ-WxRdz8wBv2VyublZgRyqeNHt5POgXDJ9yicdbd3DUddwISud2lbsdd_QQG98G7pVw
                              skipTLSVerify: true
                              skipMetricsLookup: true
                  auth:
                      allowGuestAccess: true
