apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- supportsObservedGeneration: true
  conditionMatchers:
  - type: Healthy
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: "pkg.crossplane.io/v1", kind: "Provider"}
- supportsObservedGeneration: true
  conditionMatchers:
  - type: Ready
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: "pkg.crossplane.io/v1", kind: "Provider"}
