apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      version: '*'
  interval: 10m
  releaseName: nfs-provisioner
  values:
    storageClass:
      defaultClass: true
    nfs:
      server: 192.168.1.6
      path: /volume1/kubernetes
      