apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 5m0s
  provider: generic
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
