apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: externaldns
  namespace: continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "externaldns"
spec:
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: 0.12.2+vmware.5-tkg.1
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: external-dns-values


