default:
   roles:
   - name: external-dns
   - name: cert-manager
k3s-local:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: minio
tap:
  profiles:
    - name: tap-full
      options:
        domain: tapdemo.lab.ellin.net