default:
  roles:
   - name: external-dns
   - name: cert-manager
  options:
    domain: default
k3s-local:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: minio
  options:
    minio: install
    domain: minio.lab.ellin.net
tap:
  roles:
    - name: external-dns 
    - name: tap-full
  options:
    domain: tapdemo.lab.ellin.net