default:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: contour
crossplane:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: crossplane
k3s-local:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: minio
     options:
       domain: minio.lab.ellin.net
tap-build:
  roles:
   - name: external-dns
   - name: tap-build
tap-build2:
  roles:
   - name: external-dns
   - name: tap-build
tap-test:
  roles:
   - name: external-dns
   - name: tap-full
     options:
       tap_install:
         values:
           cnrs:
             domain_name: home.lab.ellin.net
           shared:
             ingress_domain: home.lab.ellin.net

azure-tap:
  roles:
    - name: external-dns 
    - name: tap-full
      options:
        tap_install:
          values:
            cnrs:
              domain_name: tap-azure.lab.ellin.net
            shared:
              ingress_domain: tap-azure.lab.ellin.net
eks.aws-june23.us-east-2.tap-full-cluster:
  roles:
    - name: external-dns 
    - name: contour
    - name: tap-full
      options:
        tap_install:
          values:
            cnrs:
              domain_name: tap-full.lab.ellin.net
            shared:
              ingress_domain: tap-full.lab.ellin.net
tap-run-1:
  roles:
    - name: ako
      options:
        clusterName: tap-run 
    - name: external-dns 
    - name: contour
    - name: tap-run
      options:
        tap_install:
          values:
            cnrs:
              domain_name: something.lab.ellin.net
            shared:
              ingress_domain: something.lab.ellin.net
tap-view:
  roles:
    - name: ako
      options:
        clusterName: tap-view 
    - name: external-dns 
    - name: contour
    - name: tap-view
      options:
        tap_install:
          values:
            cnrs:
              domain_name: view.lab.ellin.net
            shared:
              ingress_domain: view.lab.ellin.net
