default:
  roles:
   - name: metallb
     options:
       metallb:
         addresses: 192.168.1.153-192.168.1.154
   - name: external-dns
   - name: cert-manager
   - name: contour
crossplane:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: crossplane
k3s-local:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: minio
     options:
       domain: minio.lab.ellin.net
tap:
  roles:
   - name: external-dns
   - name: tap-full
     options:
       tap_install:
         values:
           cnrs:
             domain_name: home.lab.ellin.net
           shared:
             ingress_domain: home.lab.ellin.net
tap-run-1:
  roles:
    - name: metallb
      options:
        metallb:
          addresses: 192.168.1.151-192.168.1.152
    - name: external-dns 
    - name: cert-manager
    - name: contour
    - name: tap-run
      options:
        tap_install:
          values:
            cnrs:
              domain_name: something.lab.ellin.net
            shared:
              ingress_domain: something.lab.ellin.net
