default:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: contour
  options:
    domain: default
crossplane:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: crossplane
k3s-local:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: minio
  options:
    minio: install
    domain: minio.lab.ellin.net
tap:
  roles:
   - name: external-dns
   - name: tap-full
  options:
    tap_install:
      values:
        cnrs:
          domain_name: home.lab.ellin.net
        shared:
          ingress_domain: home.lab.ellin.net
tap-run-1:
  roles:
    - name: external-dns 
    - name: tap-run
  options:
    tap_install:
      values:
        cnrs:
          domain_name: something.lab.ellin.net
        shared:
          ingress_domain: something.lab.ellin.net
