default:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: contour
aks.be7fd3a2.azuresa.crossplane:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: crossplane
k3s-local:
  roles:
   - name: external-dns
   - name: cert-manager
   - name: minio
     options:
       domain: minio.lab.ellin.net
tap-build:
  roles:
   - name: external-dns
   - name: tap-build
eks.aws-june23.us-east-2.tap-full-cluster:
  roles:
    - name: external-dns 
    - name: contour
    - name: tap-full
      options:
        tap_install:
          values:
            cnrs:
              domain_name: tap-full.lab.ellin.net
            shared:
              ingress_domain: tap-full.lab.ellin.net
aks.be7fd3a2.azuresa.tap-iterate-aks:
  roles:
    - name: external-dns 
    - name: contour
    - name: tap-iterate
      options:
        tap_install:
          values:
            cnrs:
              domain_name: tap-iterate.azure.lab.ellin.net
            shared:
              ingress_domain: tap-iterate.azure.lab.ellin.net
    - name: letsencrypt-issuer
tap-iterate:
  roles:
    - name: external-dns 
    - name: contour
    - name: tap-iterate
      options:
        tap_install:
          values:
            cnrs:
              domain_name: tap-iterate.lab.ellin.net
            shared:
              ingress_domain: tap-iterate.lab.ellin.net
    - name: letsencrypt-issuer
tap-run:
  roles:
    - name: external-dns
    - name: contour
    - name: tap-run
      options:
        tap_install:
          values:
            cnrs:
              domain_name: run-1.home.lab.ellin.net
            shared:
              ingress_domain: run-1.home.lab.ellin.net
    - name: letsencrypt-issuer
aks.be7fd3a2.azuresa.tap-run-1:
  roles:
    - name: external-dns
    - name: contour
    - name: tap-run
      options:
        tap_install:
          values:
            cnrs:
              domain_name: run-1.lab.ellin.net
            shared:
              ingress_domain: run-1.lab.ellin.net
    - name: letsencrypt-issuer
aks.be7fd3a2.azuresa.tap-view:
  roles:
    - name: external-dns 
    - name: contour
    - name: tap-view
      options:
        tap_install:
          values:
            cnrs:
              domain_name: view.azure.lab.ellin.net
            shared:
              ingress_domain: view.azure.lab.ellin.net
    - name: letsencrypt-issuer
tap-view:
  roles:
    - name: external-dns 
    - name: contour
    - name: tap-view
      options:
        tap_install:
          values:
            cnrs:
              domain_name: view.lab.ellin.net
            shared:
              ingress_domain: view.lab.ellin.net
    - name: letsencrypt-issuer
