apiVersion: ENC[AES256_GCM,data:T28=,iv:LX7SwO+2m4FuGryp8vT1HlupHPzil2tFFaXzxeO2kwg=,tag:KVhM94v0resUx7C0k/iacw==,type:str]
kind: ENC[AES256_GCM,data:/6MteoXY,iv:CldK1jjAUVrBylZWL+m57txzie4liNeYEswU4BkW/Nw=,tag:KH5fu3GK9nttwQCgvsXmrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LpNSWpO5BOptIZTZjUDEjSg4Wg==,iv:YwIRNYoE4fUH9d2ExyFi+7jeS2qdj+PXl6U+4mUHLII=,tag:TCM2opnBHT3YnWLAECmOLQ==,type:str]
    namespace: ENC[AES256_GCM,data:T5hkOPnSCCkBxuyZ,iv:g3OsSpBWVoHW9pgm3MU7Xs/TYb+vrchNcRBQcSEPruM=,tag:4i54OuXBjMlsyzCMWhHrKg==,type:str]
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:qC6RHQa5NuFl0XorNaYpOGOkSqU=,iv:UjeMG+jayw5Gcs1c7S8vWULYs1bd33hJIF4I4AT7CzY=,tag:0y0cb6MsBYLY7qeuP3mRhA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:lBvWeoLRqo2SPVssLXduN8O3Ir0Nb7EHAU+N+GGJARMRYizklgeCqA==,iv:EHnN9ICD0amWxy3Nz87LFokQAONbHp1jvLtk2OT92AI=,tag:gnYqBhK+ERLsFK53SJ8ZcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vc66ezwhcaxdy0rzu3e5w62nqmzrny323jft9c0frhtw6njhfyuq3y0cws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPKzQ0dUNDTjZtUFdQMXdo
            Yk9xTHdobTlHN2lHM21BUmpLT2h1dzk2cGdVCndVbFNyZStZampWZzRFK01YRnZt
            b0lnUUFIQmlRN0dNUDZQd3Z3eEJzVmsKLS0tIElXQlQ1WFRCWjA1WUN6VEJWMVJI
            c3dXdTZOYWl2ekhybUxrQkJkdWZOK0EKwykz2XQ46ffFG/Eq7PsTv8r3gXa9JFsp
            A04Jw+ei/USesJnQuPPZemoo8z/fYRazlp0WVez6kuDsygVhLIUUXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-22T16:52:01Z"
    mac: ENC[AES256_GCM,data:MVkh1vX7/VgYe2JGhCe34SVKsskmM07+lM0avdN4XqQz5tLE68yVKnEoDXyuHhZ+50qb6LRcnEoSga+7bGO5MPyDeQZbq7I9pY5jrqNzhsMH8RngcL6rcB+CsKkZk7WNw0yh1cfrLEdt8/NrTFZCwrykpvUMXnUhrBuR98OQP28=,iv:oLM4zKgdAPsFyztQIgGycE+E3js6aKMgX0hhEudOJr8=,tag:g5Ix22vp7AY6C5uSb+EBnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
