apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: ellin-system
  annotations:
    kapp.k14s.io/change-group: "externaldns"
spec:
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: 1.23.5+vmware.1-tkg.1 
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: external-dns-values


