apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-full
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/jeffellin/tmc-experiments
      ref: main
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt: 
      paths:
      - gitops/tap-full
  deploy:
  - kapp: {}
