apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-tap-repository
  namespace: continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: tap-repo
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.6.1
