#@ load("@ytt:data", "data")
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ako-install
  namespace: ellin-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ako
      version: 1.10.3
      sourceRef:
        kind: HelmRepository
        name: gcp
        namespace: default
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: avi-config-secret
      valuesKey: avi.yaml
  values:
    L7Settings:
      serviceType: NodePort
    AKOSettings:
      clusterName: #@ data.values.clusterName
    NetworkSettings:
      vipNetworkList:
        - networkName: DFrontEnd
          cidr: 192.168.4.0/24
    ControllerSettings:
      serviceEngineGroupName: #@ data.values.clusterName
      controllerHost: 192.168.1.190
