apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-sa
  namespace: tanzu-sync
  annotations:
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
imagePullSecrets:
  - name: install-registry-dockerconfig
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-sync-cluster-admin
  annotations:
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-sync-cluster-admin
  annotations:
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-sync-cluster-admin
subjects:
- kind: ServiceAccount
  name: sync-sa
  namespace: tanzu-sync