apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-gitops-tap-full
  namespace: continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: install-registry-export
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: install-registry-dockerconfig
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: install-registry-export
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: age-key
  namespace: continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: install-registry-export
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
spec:
  toNamespaces:
  - tanzu-sync
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: age-key
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: install-registry-export
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
spec:
  fromNamespace: continuousdelivery-resources
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tanzu-gitops-tap-full
  namespace: tanzu-sync
spec:
  fromNamespace: continuousdelivery-resources
---
