apiVersion: ENC[AES256_GCM,data:izM=,iv:LweC16KaaOVDFr2QcgTCzDIDrKWrzf0VXejVzOh0bXY=,tag:2O5/EMAjiRkSgRBaE79txQ==,type:str]
kind: ENC[AES256_GCM,data:98tPq6y/,iv:UeOihslQA61M5avqAKOdszvltMRxSIuoDE4+VK38ayY=,tag:kQOzEYc9K54lMRRz8ys7fg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1dqOZbsFl//x2Ts/hF+PubiDeqATAEx5O5S0BXU=,iv:lt6jBGq3ewOp9o3O06V1dXdyglHi8zmo/pADovo3dQE=,tag:s8Wdp65XsSNjvPzrxyeHSA==,type:str]
    namespace: ENC[AES256_GCM,data:N3YxhFkMGwo37w==,iv:GeCY5JRgkWyIsrl6nEsIIH+SWWuaj5wbMKfsvhrXnfE=,tag:OitAVLO7zzrnMlVfDJpKWQ==,type:str]
    annotations:
        kapp.k14s.io/change-group: ENC[AES256_GCM,data:TrNYllSCL+sq4FYW9nKq8Lts,iv:atEN3zafrTdukT3uSg4rxd+J8IBb0CjRe1v2ekwpbEU=,tag:ptz2lgxRHGErp1VQsw+AOw==,type:str]
        tanzu-sync.tanzu.vmware.com/variant: ENC[AES256_GCM,data:k3359w==,iv:4PFbI2ZrWilA09Kv3L08g08siXcaUFP0/H0vnaOjz0A=,tag:JZ1IAY4uOUrH2JaShWyEmA==,type:str]
        tanzu-sync.tanzu.vmware.com/version: ENC[AES256_GCM,data:+HFbitqGds5/lQ==,iv:fINqePv8spaIacO6OrPwueMOeSxCHXj64ojPk6JKNLE=,tag:KrYbo+27crz7Lmw5htAXsg==,type:str]
type: ENC[AES256_GCM,data:by2u9vCY5C9gQbSw/GctXtMlbpWQ4hK/4+Uo8lmK,iv:h/I20mSuQN1IYb8/Ebf/YYUA1KwJppBgWdt9TniyFfc=,tag:A/gLU5bBsz3QYDkXL0OEoQ==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HNiDusAewnf1+XZzHT5yD07qvDpCSeurmTj5LZxMuMIMM0UtYYKgaXXU52YMRc8e44lb1THMa5/TcTliske2brjUidhaIVI/SDx0Hg+Ff5/BbUZj9cBGBMbU1QFP2J4XXQ0I91XYrGWahb2BLyW4GiMW8LBj9J47612JXchdMYyoO38+/bx1de30ZkilgcOAH/1J1Nc1g1b1o+KJDPCjaJi1pxUamBJWUAFO9UvHLgxeIqUnQvkjrm6Mq7c=,iv:7utkMp+IQovT1GK4pvVacdGT5WwKhrRUNDUYE/HXaMM=,tag:95eQGz2n4EuAXlKQw6b2aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sul2yf3vwkkzqzq58v6cpsn9e6sn2sl09p5qqgqfr9fq70tez9nqukh9sa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSEVEajhGSCsvbjA4K1Fy
            ak9rbkRKOENycldWQitqZW5EOFowS0VBOFQ0CmI5RkluRTkyR1JXd1MwUkJVaDI5
            OVNkMmRVUTA5ZmdtNGs3Nm1pMWh5SGMKLS0tIHVITU5UaU5qeE1yQnJGbXpDWkJn
            b1dEc3Z2aGhFNHhvWFVSQ1pRT1J0bTAK1ZD2wGST6SEuz54/w6eQ9iE0oW7SbhrI
            0G6suBY12f6FN9I2ZIhnNGyPcgdfCB2yPRUmLGCjfOqh/DUi3lVkyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T17:41:06Z"
    mac: ENC[AES256_GCM,data:ozTCwOs2R4hoDia3CCIFxnK5e+PpXrAIFSK75qgmUViIOIunycAE9O4AwPDyuVw+vE19MDBp9LcnzQBdTlivD5riug/ClY/k+0cCkSbSyZ35wYuAHcoGf8LMHnx+7V1eYTdi+ACpC7o/vl965zw/ZnflEikPJPEl9bhlZEWpx6w=,iv:oFe5jZ9ItTXzQar3phUNDn9mrqeRnVmE73Z1+TdPFY0=,tag:1jBan2H+RwvFMDdyvrWxlQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
