apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: sync
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: tanzu-sync
    kapp.k14s.io/change-rule.0: upsert after upserting tanzu-sync-secrets
    kapp.k14s.io/change-rule.1: upsert after upserting install-registry-export
    kapp.k14s.io/change-rule.2: delete before deleting tanzu-sync-secrets
    kapp.k14s.io/change-rule.3: delete before deleting install-registry-export
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 1.6.0-rc.2
spec:
  serviceAccountName: sync-sa
  fetch:
  - git:
      url: git@github.com:jeffellin/single.git
      ref: origin/main
      secretRef:
        name: sync-git-ssh
      subPath: clusters/single/cluster-config
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - config
      valuesFrom:
      - path: values
  deploy:
  - kapp: {}